EntregaFinal/web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("webs.urls")),
    path('admin/', admin.site.urls),
]

EntregaFinal/web/webs/urls.py
from django.contrib import admin
from django.urls import path
from webs import views
from django.contrib.auth.views import LogoutView

app_name="webs"
urlpatterns=  [ 
    path("", views.index, name="mi_web"),
    path("inicio", views.inicio, name="Inicio"),
    path("login", views.login_request, name="Login"),
    #path("logout", LogoutView.as_view, template_name= "webs/logout.html", name="Logout"),
]

EntregaFinal/web/webs/models.py
from django.db import models

# Create your models here.

class Usuarios(models.Model):
    nombre= models.CharField(max_length=25)
    telefono=models.CharField(max_length=12)
    fecha_de_nacimiento=models.DateField()
    email=models.EmailField(max_length=25)

class Juegos(models.Model):
     nombre= models.CharField(max_length=25)
     categoria= models.CharField(max_length=25)
     empresa= models.CharField(max_length=25)
     cantidad=models.DateField

     def __str__(self):
        return f"Nombre:{self.nombre} - Categoria: {self.categoria}- Empresa: {self.empresa}- Cantidad: {self.cantidad}"

EntregaFinal/web/webs/forms.py
from django import forms
from webs.models import Usuarios
from datetime import datetime

class RegistrarUsuarios(forms.Form):
    nombre = forms.CharField(label='Nombre:', max_length=15 ,widget=forms.TextInput( attrs={ 'class':'form-control', 'placeholder':'Nombre',}))
    telefono = forms.CharField(label='Teléfono',max_length=12, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'4421234567',}))
    fecha_de_nacimiento = forms.DateField(label='Fecha de nacimiento:',widget=forms.SelectDateWidget(years=range(1900,2001),attrs={ 'class':'form-control', }))
    email = forms.EmailField(label='Email:', max_length=254, widget=forms.EmailInput(attrs={ 'class':'form-control','placeholder':'ejemplo@ejemplo.com', }))

def registrar_usuario(self):
    fecha = datetime(int(self.data['fecha_de_nacimiento_year']), (self.data['fecha_de_nacimiento_month']), int(self.data['fecha_de_nacimiento_day']))
    nuevo_usuario = Usuarios(nombre=self.data['nombre'], telefono=self.data['telefono'], fecha_de_nacimiento=fecha, email=self.data['email'])
    
    nuevo_usuario.save()

    return 'Registro exitoso'

EntregaFinal/web/webs/views.py
from django.shortcuts import render, redirect
from .forms import RegistrarUsuarios
from .models import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    mis_usuarios = Usuarios.objects.all()
    if request.method == "POST":
        register_form= RegistrarUsuarios(request.POST)
        if register_form.is_valid():
            success=register_form.registrar_usuarios(request.user)
            return redirect("./")
    else:
        register_form=RegistrarUsuarios()
        return render(request, "webs/mi_web.html", {'register_form': register_form,'usuarios': mis_usuarios}, {"Mensaje":"Usuario creado"})
    
def BaseDeDatos(request):
    game= Juegos.objects.all()
    contexto= {"Juego:":game}
    return render(request, "webs/BaseDeDatos.html", contexto)
    
def eliminardatos(request, datos__nombre):
    game= Juegos.objects.get(nombre=datos__nombre)
    game.delete()

    game= Juegos.objects.all()
    contexto= {"Juego:":game}
    return render(request, "webs/BaseDeDatos.html", contexto)

def login_request(request):
    if request.method == "POST":
       form= AuthenticationForm(request, data= request.POST)
       if form.is_valid:
            usuario= form.cleaned_data.get("Username")
            contraseña= form.cleaned_data.get("Password")
            user= authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request,"webs/inicio.html", {"Mensaje":f"Bienvenido {usuario}"})
            else:
                return render(request,"webs/inicio.html", {"Mensaje":"Error, datos incorrectos"})
    else:
        return render(request,"webs/inicio.html", {"Mensaje":"Error"})
    
    form= AuthenticationForm()
    return render(request,"webs/login.html", {"form": form} )


def inicio(request):
    return render(request, "webs/inicio.html")

EntregaFinal/web/webs/templates/webs/acercadenosotros.html
{% extends "webs/padre.html" %}
    {% load static }
{% block contenidoQueCambia %}

    <!-- Aqui se va a colocar lo que se cambia y esta asociado a esta vista-->
    <h1> Acerca de Nosotros/h1>
    <p> Nos ubicamos en capital federal, Buenos Aires</p>
    

    {% endblock %}

EntregaFinal/web/webs/templates/webs/inicio.html
{% extends "webs/padre.html" %}
    {% load static }
{% block contenidoQueCambia %}

    <!-- Aqui se va a colocar lo que se cambia y esta asociado a esta vista-->
    <h1> World Store</h1>
    <p> Somos una empresa de videojuegos a nivel mundial</p>
    <h3> Lugar de residencia: Buenos Aires, Argentina</h3>

    {% endblock %}

EntregaFinal/web/webs/templates/webs/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}

        {{form.as_p}}
        
        <button type="Submit"> Iniciar Sesion</button>

    </form>
</body>
</html>

EntregaFinal/web/webs/templates/webs/mi_web.html
<!DOCTYPE html>
<html>
<head>
  <title>Mis forms</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
    <body>
        <div class="container text-center pt-5">
            <h1>Hola</h1>        
            <p>Mi tutorial de forms</p>        
            <div class='jumbotron'>        
              <center>      
                <div class="text-left" style="max-width:500px">        
                  <form action="{% url 'webs:mi_web' %}" method="post">       
                    {% csrf_token %}        
                    {% for field in register_form %}       
                    <div class='form-group'>        
                      <label for="{{ field.name }}">{{ field.label }}</label>       
                      {{ field }}        
                    </div>        
                    {% endfor %}        
                    <br>        
                    <center><button type="submit" class="btn btn-success btn-lg">Registrar usuario</button></center>       
                  </form>       
                </div>        
              </center>       
              <br>        
              <table  class="table table-striped table-bordered">        
                <thead class="thead-dark">        
                  <tr>        
                    <th>#</th>        
                    <th>Nombre</th>        
                    <th>Telefono</th>       
                    <th>Fecha de nacimiento</th>        
                    <th>Email</th>        
                  </tr>        
                </thead>        
        <tbody>        
                  {% for user in usuarios %}        
                  <tr>        
                    <td>{{ user.id }}</td>        
                    <td>{{ user.nombre }}</td>        
                    <td>{{ user.telefono }}</td>        
                    <td>{{ user.fecha_de_nacimiento }}</td>        
                    <td>{{ user.email }}</td>        
                  </tr>        
                  {% endfor %}       
                </tbody>        
              </table>        
            </div>        
          </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

EntregaFinal/web/webs/templates/webs/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'MiRestaurante/js/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'inicio' %}">inicio</a>            
                <a class="navbar-brand" href="{% url 'Acerca De Nosotros' %}">acercadenosotros</a>
                <a class="navbar-brand" href="{% url 'Registrarse' %}">mi_web</a>                
                <a class="btn btn-primary" href="#signup">Sign Up</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Generate more leads with a professional landing page!</h1>
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form class="form-subscribe" id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <!-- Email address input-->
                                <div class="row">
                                    <div class="col">
                                        <input class="form-control form-control-lg" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                                        <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:required">Email Address is required.</div>
                                        <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
                                    </div>
                                    <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                                </div>
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        <p>To activate this form, sign up at</p>
                                        <a class="text-white" href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!--Esto es lo que va a cambiar-->

        {% block contenidoQueCambia %}
            
        {% endblock %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2022. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>